# Generated by Django 5.0.3 on 2024-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('running_low', 'Running Low'), ('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=20)),
                ('inventory', models.PositiveIntegerField()),
            ],
        ),
    ]
